=== jgallardo18/Mi/Libreria.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Libreria">
<xs:complexType>
<xs:sequence>
<xs:element name="Libro" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Autor" type="xs:string"/>
<xs:element name="Titulo" type="xs:string"/>
<xs:element name="Genero" type="xs:string"/>
<xs:element name="Editorial">
<xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="([A-Z])*"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
<xs:element name="Precio" type="xs:decimal"/>
<xs:element name="FechaPublicacion" type="xs:date"/>
<xs:element name="Descripcion">
<xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:minLength value="5"/>
      <xs:maxLength value="200"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>
</xs:sequence>
<xs:attribute name="id" type="xs:string"/>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== jgallardo18/Mi/Libreria_XSD.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Libreria.xsd">
   <Libro id="KOYHH">  
      <Autor>Fernando, Aramburu</Autor>  
      <Titulo>PATRIA</Titulo>  
      <Genero>Narrativa</Genero> 
	  <Editorial>TUSQUETS</Editorial>
      <Precio>29.95</Precio>  
      <FechaPublicacion>2017-10-10</FechaPublicacion>  
      <Descripcion>Nos habla de la imposibilidad de olvidar y de la necesidad de
	  perd√≥n en una comunidad rota por el fanatismo pol√≠tico.</Descripcion>  
   </Libro>  
   <Libro id="JHGTY">  
      <Autor>Antonio, Salas</Autor>  
      <Titulo>LOS HOMBRES QUE SUSURRAN A LAS M¡QUINAS</Titulo>  
      <Genero>No ficcion</Genero>  
	  <Editorial>ESPASA</Editorial>
      <Precio>15.95</Precio>  
      <FechaPublicacion>2015-09-18</FechaPublicacion>  
      <Descripcion>En el siglo XXI no existe nada m√°s urgente que conocer 
	  c√≥mo funciona la red. Porque todos estamos en ella.
	  Ordenador y m√≥vil son nuestro pasaporte al nuevo mundo.</Descripcion>  
   </Libro>  
   <Libro id="HGYFF">  
      <Autor>Robert, Kiyoski</Autor>  
      <Titulo>PADRE RICO, PADRE POBRE</Titulo>  
      <Genero>Lecturas complementarias</Genero> 
	  <Editorial>AGUILAR</Editorial>
      <Precio>8.95</Precio>  
      <FechaPublicacion>2004-12-31</FechaPublicacion>  
      <Descripcion>Aprender qu√© debe ense√±ar a sus hijos acerca
	  del dinero para su futuro √©xito financiero.</Descripcion>  
   </Libro>  
</Libreria>
